name: girls_care
description: "Project for girls"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^8.0.3
  get_it: ^7.6.8
  injectable: ^2.4.1
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.10+1
  elegant_notification: ^2.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  focus_detector: ^2.0.1
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  logger: ^2.2.0
  hive: ^2.2.3
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  shimmer: ^3.0.0
  keyboard_dismisser: ^3.0.0
  rxdart: ^0.27.7
  dio: ^5.4.2+1
  google_fonts: ^6.2.1
  collection: ^1.18.0
  mask_text_input_formatter: ^2.9.0
  smooth_page_indicator: ^1.1.0
  pinput: ^4.0.0
  flutter_carousel_widget: ^2.2.0
  fl_chart: ^0.67.0
  csv: ^5.1.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  change_app_package_name: ^1.1.0
  image_picker: ^1.1.1
  jwt_decoder: ^2.0.1
  flutter_launcher_icons: 0.13.1
  html: ^0.15.4
  dropdown_button2: ^2.3.9
  flutter_widget_from_html: ^0.15.1
  youtube_player_flutter: ^9.0.1
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.3.0
  web_socket_channel: ^2.4.5
  flutter_local_notifications: ^17.2.1
  firebase_messaging: ^15.0.2
  firebase_core: ^3.1.0
  infinite_scroll_pagination: ^4.0.0
  numberpicker: ^2.1.2
  flutter_screenutil: ^5.9.3
  syncfusion_flutter_datepicker: ^26.2.9
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_card_swiper: ^7.0.1
  flutter_swiper_view: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9
  freezed: ^2.5.0
  auto_route_generator: ^8.0.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    # - assets/images/

flutter_gen:
  output: lib/common/gen
  integrations:
    flutter_svg: true
